### ISSUE TITLE
description of info.pkl for phoenix14

### ISSUE THREAD

**Issue by amin07** [RenzKa/sign-segmentation#3]
Hi Katrin,
Thank you for sharing amazing works. 

Query 1. 
I was looking for the info pickle file description for phonix14, specially the 'alignment' section and the meaning of the keys such as, gloss_id_orig, gloss, gloss_part and gloss_id etc. 
Let me know if these are available or if you can help me understand. 

Query 2.
In your ICASSP paper, Table 5, when you pre trained I3D on Phoenix14, how did you obtain isolated signs? did you use the automatic alignment from reference 21?

TIA

**Comment by RenzKa** [comment]
Hi,

#### Query 1.
The information of the alignment section is extracted from the Phoenix2014 dataset, which you can find [here](https://www-i6.informatik.rwth-aachen.de/~koller/RWTH-PHOENIX/). In the downloaded folder, you can find the information at the path: `/phoenix2014-release/phoenix-2014-multisigner/annotations/automatic/`. They model each sign with 3 hidden states, which means each sign has three IDs - one for each hidden state. (This corresponds to the start, middle and end of a sign.) This information is processed into the following entries in the info.pkl file:
- `gloss_id_orig`: contains the original IDs with the hidden states.
- `gloss`: contains the name of the sign.
- `gloss_part`: contains only the information about the hidden state but not the sign.
- `gloss_id`: contains a processed version of the gloss IDs without information about the hidden states. In this version, every sign has only one ID.

#### Query 2.
Yes, we used the automatic alignment from reference 21. This is what you can find in the aforementioned dataset and our info.pkl file.

**Comment by amin07** [comment]
Great. Thanks for the explanation.
