### ISSUE TITLE
Question about training

### ISSUE THREAD

**Issue by AlbertoN3to** [RenzKa/sign-segmentation#4]
Hi! 

I wanted to know if is there a way to train with different unannotated datasets (using the pretrained model) from different sign languages.
From a glance, doesn't seem like the code supports this. 

Thanks in advance :)

**Comment by RenzKa** [comment]
Hi,

Sorry for the late reply.
Yes this does not work out-of-the-box since it depends a little bit in what format your dataset is. 

I think the easiest way is to look at the Dataloader for our datasets (folder /datasets) and adapt this for a Dataloader for your data.

Best,
Katrin
