### ISSUE TITLE
Finetuing pre-trained I3D model

### ISSUE THREAD

**Issue by by-seong-me** [RenzKa/sign-segmentation#5]
In training, is MS-TCN model only trained with pre-extracted features?

And is not I3D model fine-tuned?

**Comment by RenzKa** [comment]
Hi,

Yes we train the MS-TCN model with pre-extracted I3D features.

We fine-tune the I3D model with the BSL Corpus data. You can also see our analysis about fine-tuning on different datasets in our ICASSP paper (Table 2 and Table 5).
