### ISSUE TITLE
Can't find models.zip file in the provided google drive

### ISSUE THREAD

**Issue by jeanq1** [RenzKa/sign-segmentation#6]
Hi !
I can't seem to find the models.zip file, and the link in the download_model script seems to be broken, is there anyway you could reupload it ? 
Thank you very much in advance!

**Comment by RenzKa** [comment]
Hi,
sorry for the inconvenience and thanks for pointing this out.
I reuploaded the models folder.

**Comment by jeanq1** [comment]
Thank you very much !
